<?xml version="1.0" encoding="utf-8"?><Database Name="CMS0" Class="CFManagerDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=CMS0;Persist Security Info=True;User ID=it_hcc" SettingsObjectName="WindowsFormsApplication3.Properties.Settings" SettingsPropertyName="CMS0ConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tAccount" Member="tAccounts">
    <Type Name="tAccount">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FullName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Sex" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Birthday" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="GroupUserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BranchTypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BranchId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="Status" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="CreateAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifiedAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="tBranch_tAccount" Member="tBranch" ThisKey="BranchId" OtherKey="Id" Type="tBranch" IsForeignKey="true" />
      <Association Name="tGroupUser_tAccount" Member="tGroupUser" ThisKey="GroupUserId" OtherKey="Id" Type="tGroupUser" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tSupplier" Member="tSuppliers">
    <Type Name="tSupplier">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SupplierCode" Type="System.String" DbType="NVarChar(32)" CanBeNull="true" />
      <Column Name="SupplierName" Type="System.String" DbType="NVarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="BranchTypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="ContactName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Info" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Status" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="CreateAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifiedAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="tSupplier_tStockInput" Member="tStockInputs" ThisKey="Id" OtherKey="SupplierId" Type="tStockInput" />
    </Type>
  </Table>
  <Table Name="dbo.tBranch" Member="tBranches">
    <Type Name="tBranch">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BranchParentId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BranchCode" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
      <Column Name="BranchName" Type="System.String" DbType="NVarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="Phone" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Fax" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Info" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="BranchTypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="CreateAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifiedAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="tBranch_tAccount" Member="tAccounts" ThisKey="Id" OtherKey="BranchId" Type="tAccount" />
      <Association Name="tBranch_tCombo" Member="tCombos" ThisKey="Id" OtherKey="BranchId" Type="tCombo" />
      <Association Name="tBranch_tStockInput" Member="tStockInputs" ThisKey="Id" OtherKey="BranchId" Type="tStockInput" />
      <Association Name="tBranch_tStockOutput" Member="tStockOutputs" ThisKey="Id" OtherKey="BranchId" Type="tStockOutput" />
      <Association Name="tBranchType_tBranch" Member="tBranchType" ThisKey="BranchTypeId" OtherKey="Id" Type="tBranchType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tBranchType" Member="tBranchTypes">
    <Type Name="tBranchType">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="Website" Type="System.String" DbType="VarChar(128)" CanBeNull="true" />
      <Column Name="Status" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="CreateAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifiedAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="tBranchType_tBranch" Member="tBranches" ThisKey="Id" OtherKey="BranchTypeId" Type="tBranch" />
      <Association Name="tBranchType_tCombo" Member="tCombos" ThisKey="Id" OtherKey="BranchTypeId" Type="tCombo" />
      <Association Name="tBranchType_tProductType" Member="tProductTypes" ThisKey="Id" OtherKey="BranchTypeId" Type="tProductType" />
      <Association Name="tBranchType_tStockInput" Member="tStockInputs" ThisKey="Id" OtherKey="BranchTypeId" Type="tStockInput" />
      <Association Name="tBranchType_tProduct" Member="tProducts" ThisKey="Id" OtherKey="BranchTypeId" Type="tProduct" />
    </Type>
  </Table>
  <Table Name="dbo.tBrand" Member="tBrands">
    <Type Name="tBrand">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BrandCode" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="BrandName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="BranchTypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BranchId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="CreateAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifiedAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="tBrand_tProduct" Member="tProducts" ThisKey="Id" OtherKey="BrandId" Type="tProduct" />
    </Type>
  </Table>
  <Table Name="dbo.tColor" Member="tColors">
    <Type Name="tColor">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ColorCode" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="ColorName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="BranchTypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="CreateAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifiedAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="tColor_tProduct" Member="tProducts" ThisKey="Id" OtherKey="Color" Type="tProduct" />
    </Type>
  </Table>
  <Table Name="dbo.tCombo" Member="tCombos">
    <Type Name="tCombo">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ComboId" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="BranchTypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BranchId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ComboName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(1024)" CanBeNull="true" />
      <Column Name="TotalPrice" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="StartDate" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="EndDate" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="Status" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="CreateAt" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifiedAt" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="tBranch_tCombo" Member="tBranch" ThisKey="BranchId" OtherKey="Id" Type="tBranch" IsForeignKey="true" />
      <Association Name="tBranchType_tCombo" Member="tBranchType" ThisKey="BranchTypeId" OtherKey="Id" Type="tBranchType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tComboDetail" Member="tComboDetails">
    <Type Name="tComboDetail">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ComboId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="ProductId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Quantity" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Association Name="tProduct_tComboDetail" Member="tProduct" ThisKey="ProductId" OtherKey="Id" Type="tProduct" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tConnection" Member="tConnections">
    <Type Name="tConnection">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ServerName" Type="System.String" DbType="NVarChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(24) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Trusted_Connection" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="BranchTypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreateAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifiedAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tGroupRole" Member="tGroupRoles">
    <Type Name="tGroupRole">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RoleId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GroupId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="sView" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="sInsert" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="sModifie" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="sDel" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CreateAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifiedAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tGroupUser" Member="tGroupUsers">
    <Type Name="tGroupUser">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="GroupCode" Type="System.String" DbType="VarChar(32)" CanBeNull="true" />
      <Column Name="GroupName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="BranchTypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="CreateAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifiedAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="tGroupUser_tAccount" Member="tAccounts" ThisKey="Id" OtherKey="GroupUserId" Type="tAccount" />
    </Type>
  </Table>
  <Table Name="dbo.tProductPrice" Member="tProductPrices">
    <Type Name="tProductPrice">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProductId" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Price" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="FromDate" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="EndDate" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tProductType" Member="tProductTypes">
    <Type Name="tProductType">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProductTypeCode" Type="System.String" DbType="NVarChar(32)" CanBeNull="true" />
      <Column Name="ProductTypeName" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="ParentTypeId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BranchTypeId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Status" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="CreateAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifiedAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="tProductType_tProduct" Member="tProducts" ThisKey="Id" OtherKey="ProductTypeId" Type="tProduct" />
      <Association Name="tBranchType_tProductType" Member="tBranchType" ThisKey="BranchTypeId" OtherKey="Id" Type="tBranchType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tRole" Member="tRoles">
    <Type Name="tRole">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ModuleCode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ModuleName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Sort" Type="System.Double" DbType="Float" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tSize" Member="tSizes">
    <Type Name="tSize">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SizeCode" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="SizeName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="BranchTypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="CreateAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifiedAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="tSize_tProduct" Member="tProducts" ThisKey="Id" OtherKey="Size" Type="tProduct" />
    </Type>
  </Table>
  <Table Name="dbo.tStockInput" Member="tStockInputs">
    <Type Name="tStockInput">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="StockInputCode" Type="System.String" DbType="VarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="BranchTypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BranchId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SupplierId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BranchFromId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StockOutputCode" Type="System.String" DbType="VarChar(64)" CanBeNull="true" />
      <Column Name="InputType" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="VAT" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(1024)" CanBeNull="true" />
      <Column Name="TotalPrice" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Status" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="CreateAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifiedAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="tBranch_tStockInput" Member="tBranch" ThisKey="BranchId" OtherKey="Id" Type="tBranch" IsForeignKey="true" />
      <Association Name="tBranchType_tStockInput" Member="tBranchType" ThisKey="BranchTypeId" OtherKey="Id" Type="tBranchType" IsForeignKey="true" />
      <Association Name="tSupplier_tStockInput" Member="tSupplier" ThisKey="SupplierId" OtherKey="Id" Type="tSupplier" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tStockInputDetail" Member="tStockInputDetails">
    <Type Name="tStockInputDetail">
      <Column Name="StockInputId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ProductId" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="IsCombo" Type="System.Boolean" DbType="Bit NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ComboId" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ComboQuantity" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Association Name="tProduct_tStockInputDetail" Member="tProduct" ThisKey="ProductId" OtherKey="Id" Type="tProduct" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tStockInventory" Member="tStockInventories">
    <Type Name="tStockInventory">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BranchTypeId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BranchId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ProductId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="QuantityIn" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="QuantityOut" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="CreateAt" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="Status" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Association Name="tProduct_tStockInventory" Member="tProduct" ThisKey="ProductId" OtherKey="Id" Type="tProduct" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tHourGold" Member="tHourGolds">
    <Type Name="tHourGold">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BranchTypeId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BranchId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(1024)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="FromDate" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="ToDate" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="FromHour" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="ToHour" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="MinBill" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="SaleType" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="SaleValue" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Status" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="CreateAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifiedAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="tHourGold_tHourGoldDetail" Member="tHourGoldDetails" ThisKey="Id" OtherKey="HourGoldId" Type="tHourGoldDetail" />
    </Type>
  </Table>
  <Table Name="dbo.tHourGoldDetail" Member="tHourGoldDetails">
    <Type Name="tHourGoldDetail">
      <Column Name="HourGoldId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ProductId" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="tHourGold_tHourGoldDetail" Member="tHourGold" ThisKey="HourGoldId" OtherKey="Id" Type="tHourGold" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tDiscount" Member="tDiscounts">
    <Type Name="tDiscount">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BranchTypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DiscountName" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="DiscountType" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="DiscountNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DiscountValue" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="StartDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EndDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="OrderMinValue" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Status" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="CreateAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifiedAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="tDiscount_tDiscountList" Member="tDiscountLists" ThisKey="Id" OtherKey="DiscountId" Type="tDiscountList" />
    </Type>
  </Table>
  <Table Name="dbo.tDiscountList" Member="tDiscountLists">
    <Type Name="tDiscountList">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DiscountId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DiscountCode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="IsUsing" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ModifiedAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="tDiscount_tDiscountList" Member="tDiscount" ThisKey="DiscountId" OtherKey="Id" Type="tDiscount" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tMember" Member="tMembers">
    <Type Name="tMember">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MemberCode" Type="System.String" DbType="NVarChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="MemberType" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="MemberName" Type="System.String" DbType="NVarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="Birthday" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="Sex" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
      <Column Name="JoinCreateAt" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="BranchTypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CountryId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CountryName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DistrictId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DistrictName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="Status" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="CreateAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifiedAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="r_name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="r_phone" Type="System.String" DbType="VarChar(16)" CanBeNull="true" />
      <Column Name="r_add" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="r_countryid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="r_districtid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="r_countryname" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="r_districtname" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="p_name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="p_phone" Type="System.String" DbType="VarChar(16)" CanBeNull="true" />
      <Column Name="p_add" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="p_districtid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="p_countryid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="p_countryname" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="p_districtname" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="tMember_tStockOutput" Member="tStockOutputs" ThisKey="Id" OtherKey="MemberId" Type="tStockOutput" />
    </Type>
  </Table>
  <Table Name="dbo.tPersonnel" Member="tPersonnels">
    <Type Name="tPersonnel">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BranchTypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BranchId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Sex" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Birthday" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="Status" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="CreateAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifiedAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tStockOutputDetail" Member="tStockOutputDetails">
    <Type Name="tStockOutputDetail">
      <Column Name="StockOutputId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ProductId" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Discount" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DiscountPercent" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IsCombo" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ComboId" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ComboQuantity" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Association Name="tProduct_tStockOutputDetail" Member="tProduct" ThisKey="ProductId" OtherKey="Id" Type="tProduct" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tUnit" Member="tUnits">
    <Type Name="tUnit">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BranchTypeId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UnitCode" Type="System.String" DbType="NVarChar(24)" CanBeNull="true" />
      <Column Name="UnitName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Status" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="CreateAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifiedAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tCapacity" Member="tCapacities">
    <Type Name="tCapacity">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BranchTypeId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CapacityCode" Type="System.String" DbType="NVarChar(24)" CanBeNull="true" />
      <Column Name="CapacityName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="Status" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="CreateAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifiedAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tProduct" Member="tProducts">
    <Type Name="tProduct">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CodeId" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="YearId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ProductCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ProductName" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="ParentProductTypeId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ProductTypeId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ProductTypeCode" Type="System.String" DbType="VarChar(32)" CanBeNull="true" />
      <Column Name="BranchTypeId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SupplierId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Image" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="ImageZoom" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="NoteSale" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
      <Column Name="Tag" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="Score" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="Content" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="BrandId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Color" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Size" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UnitId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Material" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="Composition" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="CountryId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CountryName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ExpiryDate" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="Status" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="CreateAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifiedAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="tProduct_tComboDetail" Member="tComboDetails" ThisKey="Id" OtherKey="ProductId" Type="tComboDetail" />
      <Association Name="tProduct_tStockInputDetail" Member="tStockInputDetails" ThisKey="Id" OtherKey="ProductId" Type="tStockInputDetail" />
      <Association Name="tProduct_tStockInventory" Member="tStockInventories" ThisKey="Id" OtherKey="ProductId" Type="tStockInventory" />
      <Association Name="tProduct_tStockOutputDetail" Member="tStockOutputDetails" ThisKey="Id" OtherKey="ProductId" Type="tStockOutputDetail" />
      <Association Name="tBranchType_tProduct" Member="tBranchType" ThisKey="BranchTypeId" OtherKey="Id" Type="tBranchType" IsForeignKey="true" />
      <Association Name="tBrand_tProduct" Member="tBrand" ThisKey="BrandId" OtherKey="Id" Type="tBrand" IsForeignKey="true" />
      <Association Name="tColor_tProduct" Member="tColor" ThisKey="Color" OtherKey="Id" Type="tColor" IsForeignKey="true" />
      <Association Name="tProductType_tProduct" Member="tProductType" ThisKey="ProductTypeId" OtherKey="Id" Type="tProductType" IsForeignKey="true" />
      <Association Name="tSize_tProduct" Member="tSize" ThisKey="Size" OtherKey="Id" Type="tSize" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tStockOutput" Member="tStockOutputs">
    <Type Name="tStockOutput">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="StockCode" Type="System.String" DbType="NVarChar(32)" CanBeNull="true" />
      <Column Name="BranchTypeId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BranchId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BranchToId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RefId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MemberId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DiscountId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DiscountCode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="OutputType" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(1024)" CanBeNull="true" />
      <Column Name="TotalPrice" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Total" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="CustomePay" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="CustomeReturn" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Discount" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DiscountPercent" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Status" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="PaymentType" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="AccountId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreateAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifiedAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="tBranch_tStockOutput" Member="tBranch" ThisKey="BranchId" OtherKey="Id" Type="tBranch" IsForeignKey="true" />
      <Association Name="tMember_tStockOutput" Member="tMember" ThisKey="MemberId" OtherKey="Id" Type="tMember" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tFeedback" Member="tFeedbacks">
    <Type Name="tFeedback">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BranchTypeId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BranchId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MemberId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OrderId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OrderAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Content" Type="System.String" DbType="NVarChar(1024)" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreateAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.sp_Account_Load" Method="sp_Account_Load">
    <ElementType Name="sp_Account_LoadResult">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FullName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Sex" Type="System.String" DbType="NVarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Birthday" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="GroupName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="BranchName" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
      <Column Name="BranchTypeName" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_Product_Load" Method="sp_Product_Load">
    <Parameter Name="branchtype" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_Product_LoadResult">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="CodeId" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="ProductCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ProductName" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="Price" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ProductTypeName" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_StockInput_GetCodeId" Method="sp_StockInput_GetCodeId">
    <ElementType Name="sp_StockInput_GetCodeIdResult">
      <Column Name="CodeId" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_StockInput_InsertData" Method="sp_StockInput_InsertData">
    <Parameter Name="inputCode" Type="System.String" DbType="VarChar(64)" />
    <Parameter Name="branchType" Type="System.Int32" DbType="Int" />
    <Parameter Name="branchId" Type="System.Int32" DbType="Int" />
    <Parameter Name="branchFrom" Type="System.Int32" DbType="Int" />
    <Parameter Name="outputCode" Type="System.String" DbType="VarChar(64)" />
    <Parameter Name="note" Type="System.String" DbType="NVarChar(1024)" />
    <Parameter Name="createBy" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_StockInput_InsertDataResult">
      <Column Name="stt" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_StockOutput_GetCodeId" Method="sp_StockOutput_GetCodeId">
    <ElementType Name="sp_StockOutput_GetCodeIdResult">
      <Column Name="CodeId" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_SummaryStock_Print" Method="sp_SummaryStock_Print">
    <Parameter Name="branchType" Type="System.Int32" DbType="Int" />
    <Parameter Name="branchId" Type="System.Int32" DbType="Int" />
    <Parameter Name="fromdate" Type="System.DateTime" DbType="SmallDateTime" />
    <Parameter Name="todate" Type="System.DateTime" DbType="SmallDateTime" />
    <ElementType Name="sp_SummaryStock_PrintResult">
      <Column Name="BranchType" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
      <Column Name="BranchName" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="InputType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StockCode" Type="System.String" DbType="NVarChar(32)" CanBeNull="true" />
      <Column Name="OutputType" Type="System.String" DbType="NVarChar(11) NOT NULL" CanBeNull="false" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(1024)" CanBeNull="true" />
      <Column Name="TotalPrice" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(7) NOT NULL" CanBeNull="false" />
      <Column Name="CreateAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_SummaryStockInput" Method="sp_SummaryStockInput">
    <Parameter Name="branchType" Type="System.Int32" DbType="Int" />
    <Parameter Name="branchId" Type="System.Int32" DbType="Int" />
    <Parameter Name="fromdate" Type="System.DateTime" DbType="SmallDateTime" />
    <Parameter Name="todate" Type="System.DateTime" DbType="SmallDateTime" />
    <ElementType Name="sp_SummaryStockInputResult">
      <Column Name="InputType" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="StockCode" Type="System.String" DbType="VarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="CreateAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="BranchName" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="TotalPrice" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="OutputType" Type="System.String" DbType="NVarChar(12) NOT NULL" CanBeNull="false" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(1024)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(7) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_ReportInventory" Method="sp_ReportInventory">
    <Parameter Name="branchType" Type="System.Int32" DbType="Int" />
    <Parameter Name="branchId" Type="System.Int32" DbType="Int" />
    <Parameter Name="fromDate" Type="System.DateTime" DbType="SmallDateTime" />
    <Parameter Name="toDate" Type="System.DateTime" DbType="SmallDateTime" />
    <ElementType Name="sp_ReportInventoryResult">
      <Column Name="ProductId" Type="System.String" DbType="VarChar(32)" CanBeNull="true" />
      <Column Name="ProductCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ProductName" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="Pre" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="QuantityInput" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="QuantityOutput" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Total" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_getBillStockOutputInternalById" Method="sp_getBillStockOutputInternalById">
    <Parameter Name="code" Type="System.String" DbType="VarChar(20)" />
    <ElementType Name="sp_getBillStockOutputInternalByIdResult">
      <Column Name="OutputType" Type="System.String" DbType="NVarChar(22) NOT NULL" CanBeNull="false" />
      <Column Name="BranchType" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="BranchName" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="BranchToName" Type="System.String" DbType="NVarChar(144)" CanBeNull="true" />
      <Column Name="StockCode" Type="System.String" DbType="NVarChar(32)" CanBeNull="true" />
      <Column Name="TotalPrice" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="CreateAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ProductName" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Price" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="IsCombo" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ComboId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="ProductId" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_getComboList" Method="sp_getComboList">
    <Parameter Name="branchType" Type="System.Int32" DbType="Int" />
    <Parameter Name="branchId" Type="System.Int32" DbType="Int" />
    <Parameter Name="year" Type="System.Int32" DbType="Int" />
    <Parameter Name="month" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_getComboListResult">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="ComboName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(1024)" CanBeNull="true" />
      <Column Name="TotalPrice" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="StartDate" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="EndDate" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="CodeId" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="ProductCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ProductName" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="Quantity" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_StockOutput_Return" Method="sp_StockOutput_Return">
    <Parameter Name="stock_code_old" Type="System.String" DbType="NVarChar(32)" />
    <Parameter Name="user" Type="System.Int32" DbType="Int" />
    <Parameter Name="stockcode_in" Type="System.String" DbType="NVarChar(32)" />
    <Parameter Name="stockcode_out" Type="System.String" DbType="NVarChar(32)" />
    <Parameter Name="total_price_out" Type="System.Double" DbType="Float" />
    <Parameter Name="note" Type="System.String" DbType="NVarChar(1024)" />
    <Parameter Name="brachId" Type="System.Int32" DbType="Int" />
    <Parameter Name="branchType" Type="System.Int32" DbType="Int" />
    <Parameter Name="code_in" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="code_out" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="ton_out" Type="System.String" DbType="NVarChar(MAX)" />
    <ElementType Name="sp_StockOutput_ReturnResult">
      <Column Name="stt" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_Product_Search" Method="sp_Product_Search">
    <Parameter Name="branchType" Type="System.Int32" DbType="Int" />
    <Parameter Name="type" Type="System.Int32" DbType="Int" />
    <Parameter Name="code" Type="System.String" DbType="NVarChar(128)" />
    <ElementType Name="sp_Product_SearchResult">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="ProductTypeName" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="CodeId" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="SKU" Type="System.String" DbType="NVarChar(156)" CanBeNull="true" />
      <Column Name="ProductCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ProductName" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="Price" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_CheckInventoryByProductCode" Method="sp_CheckInventoryByProductCode">
    <Parameter Name="branchType" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="code" Type="System.String" DbType="VarChar(20)" />
    <ElementType Name="sp_CheckInventoryByProductCodeResult">
      <Column Name="BranchName" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="Total" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_loadGift" Method="sp_loadGift">
    <Parameter Name="branchType" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="branch" Type="System.String" DbType="VarChar(10)" />
    <ElementType Name="sp_loadGiftResult">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BranchName" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(1024)" CanBeNull="true" />
      <Column Name="FromDate" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="ToDate" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="FromHour" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="ToHour" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="SaleType" Type="System.String" DbType="NVarChar(18) NOT NULL" CanBeNull="false" />
      <Column Name="SaleValue" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_loadGiftDetail" Method="sp_loadGiftDetail">
    <Parameter Name="saleId" Type="System.String" DbType="VarChar(20)" />
    <ElementType Name="sp_loadGiftDetailResult">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProductId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="CodeId" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="ProductCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ProductName" Type="System.String" DbType="NVarChar(234)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_checkDiscount" Method="sp_checkDiscount">
    <Parameter Name="branchType" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="discountCode" Type="System.String" DbType="VarChar(20)" />
    <ElementType Name="sp_checkDiscountResult">
      <Column Name="Id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DiscountCode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DiscountType" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="DiscountValue" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="OrderMinValue" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_loadRevenueByPersonnel" Method="sp_loadRevenueByPersonnel">
    <Parameter Name="branchType" Type="System.Int32" DbType="Int" />
    <Parameter Name="personalId" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="fromdate" Type="System.DateTime" DbType="SmallDateTime" />
    <Parameter Name="todate" Type="System.DateTime" DbType="SmallDateTime" />
    <ElementType Name="sp_loadRevenueByPersonnelResult">
      <Column Name="Code" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Birthday" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="BranchName" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
      <Column Name="Total" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_getBarCode" Method="sp_getBarCode">
    <Parameter Name="branchType" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="code" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="sp_getBarCodeResult">
      <Column Name="Code" Type="System.String" DbType="VarChar(22)" CanBeNull="true" />
      <Column Name="CodeId" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="ProductCode" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="ProductName" Type="System.String" DbType="NVarChar(156)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_getBillById" Method="sp_getBillById">
    <Parameter Name="code" Type="System.String" DbType="VarChar(20)" />
    <ElementType Name="sp_getBillByIdResult">
      <Column Name="OutputType" Type="System.String" DbType="NVarChar(14) NOT NULL" CanBeNull="false" />
      <Column Name="BranchType" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="BranchName" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="MemberName" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="StockCode" Type="System.String" DbType="NVarChar(32)" CanBeNull="true" />
      <Column Name="TotalPrice" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Total" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TotalDiscount" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="CustomePay" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="CustomeReturn" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="CreateAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ProductCode" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="ProductName" Type="System.String" DbType="NVarChar(234)" CanBeNull="true" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Price" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="IsCombo" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ComboId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="ProductId" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="Discount" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="DiscountPercent" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(70)" CanBeNull="true" />
      <Column Name="Score" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Doitra" Type="System.String" DbType="NVarChar(1024)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_getBillCode_Return" Method="sp_getBillCode_Return">
    <Parameter Name="branchId" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="code" Type="System.String" DbType="NVarChar(32)" />
    <ElementType Name="sp_getBillCode_ReturnResult">
      <Column Name="ProductId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="CodeId" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="ProductCode" Type="System.String" DbType="NVarChar(90)" CanBeNull="true" />
      <Column Name="ProductName" Type="System.String" DbType="NVarChar(234)" CanBeNull="true" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Price" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Discount" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DiscountPercent" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="IsCombo" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MemberName" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="CreateAt" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Branch" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="Total" Type="System.Double" DbType="Float" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_StockInput_Get" Method="sp_StockInput_Get">
    <Parameter Name="branchId" Type="System.Int32" DbType="Int" />
    <Parameter Name="branchType" Type="System.Int32" DbType="Int" />
    <Parameter Name="code" Type="System.String" DbType="VarChar(20)" />
    <ElementType Name="sp_StockInput_GetResult">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(1024)" CanBeNull="true" />
      <Column Name="CreateAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="BranchId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BranchName" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
      <Column Name="ProductId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CodeId" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="ProductCode" Type="System.String" DbType="NVarChar(90)" CanBeNull="true" />
      <Column Name="ProductName" Type="System.String" DbType="NVarChar(234)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_getBillStockInputInternalById" Method="sp_getBillStockInputInternalById">
    <Parameter Name="code" Type="System.String" DbType="VarChar(20)" />
    <ElementType Name="sp_getBillStockInputInternalByIdResult">
      <Column Name="OutputType" Type="System.String" DbType="NVarChar(22) NOT NULL" CanBeNull="false" />
      <Column Name="BranchType" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="BranchName" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="BranchToName" Type="System.String" DbType="NVarChar(141)" CanBeNull="true" />
      <Column Name="StockCode" Type="System.String" DbType="VarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="CreateAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ProductName" Type="System.String" DbType="NVarChar(234)" CanBeNull="true" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsCombo" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ComboId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="ProductId" Type="System.String" DbType="NVarChar(113)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_getBarCodeCnice" Method="sp_getBarCodeCnice">
    <Parameter Name="branchType" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="code" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="sp_getBarCodeCniceResult">
      <Column Name="Code" Type="System.String" DbType="VarChar(22)" CanBeNull="true" />
      <Column Name="CodeId" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="ProductCode" Type="System.String" DbType="NVarChar(14) NOT NULL" CanBeNull="false" />
      <Column Name="ProductName" Type="System.String" DbType="NVarChar(565)" CanBeNull="true" />
      <Column Name="Country" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Brand" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_ProductCnice_Search" Method="sp_ProductCnice_Search">
    <Parameter Name="branchType" Type="System.Int32" DbType="Int" />
    <Parameter Name="type" Type="System.Int32" DbType="Int" />
    <Parameter Name="code" Type="System.String" DbType="NVarChar(128)" />
    <ElementType Name="sp_ProductCnice_SearchResult">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="ProductTypeName" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="ProductCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ProductName" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="BrandName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CountryName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CapacityName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UnitName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_ReportInventoryCNice" Method="sp_ReportInventoryCNice">
    <Parameter Name="branchType" Type="System.Int32" DbType="Int" />
    <Parameter Name="branchId" Type="System.Int32" DbType="Int" />
    <Parameter Name="fromDate" Type="System.DateTime" DbType="SmallDateTime" />
    <Parameter Name="toDate" Type="System.DateTime" DbType="SmallDateTime" />
    <ElementType Name="sp_ReportInventoryCNiceResult">
      <Column Name="ProductId" Type="System.String" DbType="VarChar(32)" CanBeNull="true" />
      <Column Name="ProductCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ProductName" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="BrandName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UnitName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CountryName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CapacityName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Pre" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="QuantityInput" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="QuantityOutput" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Total" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_getBillByIdCnice" Method="sp_getBillByIdCnice">
    <Parameter Name="code" Type="System.String" DbType="VarChar(20)" />
    <ElementType Name="sp_getBillByIdCniceResult">
      <Column Name="OutputType" Type="System.String" DbType="NVarChar(14) NOT NULL" CanBeNull="false" />
      <Column Name="BranchType" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="BranchName" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="MemberName" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="StockCode" Type="System.String" DbType="NVarChar(32)" CanBeNull="true" />
      <Column Name="TotalPrice" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Total" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TotalDiscount" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="CustomePay" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="CustomeReturn" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="CreateAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ProductCode" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="ProductName" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="BrandName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UnitName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CapacityName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CountryName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Price" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="IsCombo" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ComboId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="ProductId" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="Discount" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="DiscountPercent" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Score" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Doitra" Type="System.String" DbType="NVarChar(1024)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_getBillStockOutputInternalByIdCnice" Method="sp_getBillStockOutputInternalByIdCnice">
    <Parameter Name="code" Type="System.String" DbType="VarChar(20)" />
    <ElementType Name="sp_getBillStockOutputInternalByIdCniceResult">
      <Column Name="OutputType" Type="System.String" DbType="NVarChar(22) NOT NULL" CanBeNull="false" />
      <Column Name="BranchType" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="BranchName" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="BranchToName" Type="System.String" DbType="NVarChar(144)" CanBeNull="true" />
      <Column Name="StockCode" Type="System.String" DbType="NVarChar(32)" CanBeNull="true" />
      <Column Name="TotalPrice" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="CreateAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ProductName" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="BrandName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CountryName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UnitName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CapacityName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Price" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="IsCombo" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ComboId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="ProductId" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_getBillStockInputInternalByIdCnice" Method="sp_getBillStockInputInternalByIdCnice">
    <Parameter Name="code" Type="System.String" DbType="VarChar(20)" />
    <ElementType Name="sp_getBillStockInputInternalByIdCniceResult">
      <Column Name="OutputType" Type="System.String" DbType="NVarChar(22) NOT NULL" CanBeNull="false" />
      <Column Name="BranchType" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="BranchName" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="BranchToName" Type="System.String" DbType="NVarChar(141)" CanBeNull="true" />
      <Column Name="StockCode" Type="System.String" DbType="VarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="CreateAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ProductName" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="BrandName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CountryName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UnitName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CapacityName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsCombo" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ComboId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="ProductId" Type="System.String" DbType="NVarChar(73)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_StockInput_GetCnice" Method="sp_StockInput_GetCnice">
    <Parameter Name="branchId" Type="System.Int32" DbType="Int" />
    <Parameter Name="branchType" Type="System.Int32" DbType="Int" />
    <Parameter Name="code" Type="System.String" DbType="VarChar(20)" />
    <ElementType Name="sp_StockInput_GetCniceResult">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(1024)" CanBeNull="true" />
      <Column Name="CreateAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="BranchId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BranchName" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
      <Column Name="ProductId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CodeId" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="ProductCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ProductName" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="BrandName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CountryName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UnitName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CapacityName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_getBillCode_ReturnCnice" Method="sp_getBillCode_ReturnCnice">
    <Parameter Name="branchId" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="code" Type="System.String" DbType="NVarChar(32)" />
    <ElementType Name="sp_getBillCode_ReturnCniceResult">
      <Column Name="ProductId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="CodeId" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="ProductCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ProductName" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="BrandName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CountryName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UnitName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CapacityName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Price" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Discount" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DiscountPercent" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="IsCombo" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MemberName" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="CreateAt" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Branch" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="Total" Type="System.Double" DbType="Float" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_getTemphuCnice" Method="sp_getTemphuCnice">
    <Parameter Name="branchType" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="code" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="sp_getTemphuCniceResult">
      <Column Name="Temp" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_Product_GetDetailByCodeIdCnice" Method="sp_Product_GetDetailByCodeIdCnice">
    <Parameter Name="branchType" Type="System.Int32" DbType="Int" />
    <Parameter Name="branchId" Type="System.Int32" DbType="Int" />
    <Parameter Name="codeid" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="quantity" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_Product_GetDetailByCodeIdCniceResult">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="ProductCode" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ProductName" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="UnitId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UnitName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="BrandName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CountryName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CapacityName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Price" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="IsCombo" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Discount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="saleType" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="saleValue" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="priceSale" Type="System.Double" DbType="Float" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_ReportRevenue" Method="sp_ReportRevenue">
    <Parameter Name="branchType" Type="System.Int32" DbType="Int" />
    <Parameter Name="branchId" Type="System.Int32" DbType="Int" />
    <Parameter Name="fromDate" Type="System.DateTime" DbType="SmallDateTime" />
    <Parameter Name="toDate" Type="System.DateTime" DbType="SmallDateTime" />
    <Parameter Name="paymentType" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_ReportRevenueResult">
      <Column Name="StockCode" Type="System.String" DbType="NVarChar(32)" CanBeNull="true" />
      <Column Name="MemberName" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="Total" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TotalDiscount" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TotalPrice" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="CreateAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(1024)" CanBeNull="true" />
      <Column Name="PaymentType" Type="System.String" DbType="NVarChar(12) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_SummaryStock" Method="sp_SummaryStock">
    <Parameter Name="branchType" Type="System.Int32" DbType="Int" />
    <Parameter Name="branchId" Type="System.Int32" DbType="Int" />
    <Parameter Name="fromdate" Type="System.DateTime" DbType="SmallDateTime" />
    <Parameter Name="todate" Type="System.DateTime" DbType="SmallDateTime" />
    <Parameter Name="billcode" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="member" Type="System.String" DbType="NVarChar(64)" />
    <Parameter Name="paymentType" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_SummaryStockResult">
      <Column Name="InputType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StockCode" Type="System.String" DbType="NVarChar(32)" CanBeNull="true" />
      <Column Name="BranchName" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="OutputType" Type="System.String" DbType="NVarChar(11) NOT NULL" CanBeNull="false" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(1024)" CanBeNull="true" />
      <Column Name="TotalPrice" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(7) NOT NULL" CanBeNull="false" />
      <Column Name="CreateAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="Total" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Discount" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="MemberName" Type="System.String" DbType="NVarChar(87)" CanBeNull="true" />
      <Column Name="PaymentType" Type="System.String" DbType="NVarChar(12) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>